version: '3.7'

services:
  minio1:
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=flag1234
    command: server http://minio{1...4}/data{1...2} --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin-super-secret-password-do-not-use
    command: server http://minio{1...4}/data{1...2} --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin-super-secret-password-do-not-use
    command: server http://minio{1...4}/data{1...2} --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin-super-secret-password-do-not-use
    command: server http://minio{1...4}/data{1...2} --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2: